# Generated by Django 5.0.4 on 2024-04-19 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_remove_gamesession_owner_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gamesession'),
        ),
    ]
